document.write('\n<!-- Copyright DoubleClick Inc., All rights reserved. -->\n<!-- This code was autogenerated @ Wed Jan 27 06:10:59 EST 2010 -->\n<script src=\"http://s0.2mdn.net/879366/flashwrite_1_2.js\"><\/script>');document.write('\n  \n');

 
var dcallowscriptaccess = 'never';
var plugin = false;
var advurl = 'http://www.economist.com/classifieds';
var alttext = '';
var dcgif = 'http://s0.2mdn.net/2073642/ecom_classifieds_125x125_swap_27_jan.gif';
var dccreativewidth = '125';
var dcwmode = 'opaque';
var imgurl = 'http://www.economist.com/classifieds';
var target = '_blank';
var dcbgcolor = '';
var dcswf = 'http://s0.2mdn.net/2073642/ecom_classifieds_125x125_swap_27_jan.swf';
var dcminversion = '9';
var dccreativeheight = '125';
function checkFlash(v){ 
var y, x, s="Shockwave", f="Flash", o="object", u="undefined", np=navigator.plugins, nm=navigator.mimeTypes, nmd="application/x-shockwave-flash"; 
v = Math.max(Math.floor(v) || 0, 6); // check if v is a number and use Flash Player 6 as the minimum player version 
if(typeof np!=u&&typeof np[s+" "+f]==o&&(x=np[s+" "+f].description)&&!(typeof nm!=u&&nm[nmd]&&!nm[nmd].enabledPlugin)){ 
if(v<=x.match(/Shockwave Flash (\d+)/)[1])return true;} 
else if(typeof window.ActiveXObject!=u){ 
for(y=16;y>=v;y--){ 
try{x=new ActiveXObject(s+f+"."+s+f+"."+y);if((x!=null)&&(typeof x==o))return true;}catch(e){}} 
} 
return false;}

if ( checkFlash(dcminversion) )  {  
adcode = '<OBJECT classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"'+
' ID=FLASH_AD WIDTH="'+ dccreativewidth +'" HEIGHT="'+ dccreativeheight +'">'+
'<PARAM NAME=movie VALUE="' + dcswf  +'"><PARAM NAME=quality VALUE=high><PARAM NAME=bgcolor VALUE=#'+ dcbgcolor +'><PARAM NAME=wmode VALUE='+ dcwmode +'><PARAM NAME="AllowScriptAccess" VALUE="'+dcallowscriptaccess+'">'+
 '<EMBED src="' + dcswf  +'" quality=high wmode='+dcwmode+
' swLiveConnect=TRUE WIDTH="'+ dccreativewidth +'" HEIGHT="'+ dccreativeheight +'" bgcolor=#'+ dcbgcolor+
' TYPE="application/x-shockwave-flash" AllowScriptAccess="'+dcallowscriptaccess+'"></EMBED></OBJECT>';
if(('j'!="j")&&(typeof dclkFlashWrite!="undefined")){dclkFlashWrite(adcode);}else{document.write(adcode);} 
} else { 
document.write('<A TARGET="_blank" HREF="http://ad.doubleclick.net/click%3Bh%3Dv8/3af1/3/0/%2a/y%3B219473161%3B0-0%3B1%3B59875002%3B3-125/125%3B35278566/35296384/1%3B%3B%7Esscs%3D%3fhttp://www.economist.com/classifieds"><IMG SRC="' + dcgif + '" alt="" BORDER=0></A>');
}
//-->  

document.write('\n<NOSCRIPT><a target=\"_blank\" href=\"http://ad.doubleclick.net/click%3Bh%3Dv8/3af1/3/0/%2a/y%3B219473161%3B0-0%3B1%3B59875002%3B3-125/125%3B35278566/35296384/1%3B%3B%7Esscs%3D%3fhttp://www.economist.com/classifieds\"><img src=\"http://s0.2mdn.net/2073642/ecom_classifieds_125x125_swap_27_jan.gif\"  border=\"0\" alt=\"\" ></a></NOSCRIPT>');
