try{
function i(b){throw b;}var k=void 0,l=!0,m=null,o=!1,r;function s(b,a,c){b=b.split(".");c=c||t;!(b[0]in c)&&c.execScript&&c.execScript("var "+b[0]);for(var d;b.length&&(d=b.shift());)!b.length&&a!==k?c[d]=a:c=c[d]?c[d]:c[d]={}}
function aa(b){var a=typeof b;if("object"==a)if(b){if(b instanceof Array)return"array";if(b instanceof Object)return a;var c=Object.prototype.toString.call(b);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof b.length&&"undefined"!=typeof b.splice&&"undefined"!=typeof b.propertyIsEnumerable&&!b.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof b.call&&"undefined"!=typeof b.propertyIsEnumerable&&!b.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==a&&"undefined"==typeof b.call)return"object";return a}function u(b){return"array"==aa(b)}function v(b){var a=aa(b);return"array"==a||"object"==a&&"number"==typeof b.length}function x(b){return"string"==typeof b}function ba(b){return b[ca]||(b[ca]=++da)}function ea(b,a,c){return b.call.apply(b.bind,arguments)}
function fa(b,a,c){b||i(Error());if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return b.apply(a,c)}}return function(){return b.apply(a,arguments)}}function z(b,a,c){z=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ea:fa;return z.apply(m,arguments)}
function A(b,a){function c(){}c.prototype=a.prototype;b.M=a.prototype;b.prototype=new c;b.prototype.constructor=b}function ga(b,a){0<=B(b,a)||b.push(a)}function ha(b,a){var c=B(b,a),d;(d=0<=c)&&C.splice.call(b,c,1);return d}function ia(b){return C.concat.apply(C,arguments)}function ja(b){if(u(b))return ia(b);for(var a=[],c=0,d=b.length;c<d;c++)a[c]=b[c];return a}
function ka(b,a){for(var c=1;c<arguments.length;c++){var d=arguments[c],f;if(u(d)||(f=v(d))&&d.hasOwnProperty("callee"))b.push.apply(b,d);else if(f)for(var e=b.length,g=d.length,h=0;h<g;h++)b[e+h]=d[h];else b.push(d)}}function la(b,a){for(var c=a||b,d={},f=0,e=0;e<b.length;){var g=b[e++],h=aa(g),h="object"==h||"array"==h||"function"==h?"o"+ba(g):(typeof g).charAt(0)+g;Object.prototype.hasOwnProperty.call(d,h)||(d[h]=l,c[f++]=g)}c.length=f}
function ma(b){var a=[],c=0,d;for(d in b)a[c++]=b[d];return a}function na(){return t.navigator?t.navigator.userAgent:m}function D(){}function oa(b){b&&"function"==typeof b.K&&b.K()}function pa(b){for(var a=0,c=arguments.length;a<c;++a){var d=arguments[a];v(d)?pa.apply(m,d):oa(d)}}function qa(b){return function(){i(Error(b))}}function ra(){}function sa(b,a){this.Xa=b;this.g=a;this.f=[];this.d=[];this.b=[]}
function ta(b,a){var c=new b.h;a();b.oa=c;c=(c=!!ua(b,b.b,a()))||!!ua(b,b.f,a());c||(b.d.length=0);return c}function va(b,a){var c=ua(b,b.d,a);c&&window.setTimeout(qa("Module errback failures: "+c),0);b.b.length=0;b.f.length=0}function ua(b,a,c){for(var b=[],d=0;d<a.length;d++)try{a[d].execute(c)}catch(f){b.push(f)}a.length=0;return b.length?b:m}function E(){this.B={};this.f=[];this.d=[];this.b=[];this.h=[];this.n={};this.g=this.k=new sa([],"")}
function wa(b){var a=0<b.f.length;a!=b.bb&&(xa(b,a?"active":"idle"),b.bb=a);a=0<b.h.length;a!=b.kb&&(xa(b,a?"userActive":"userIdle"),b.kb=a)}function ya(b,a,c,d){c||(b.va=0);c=za(b,a);b.f=c;b.Ta?b.d=a:b.d=ja(c);wa(b);a=z(b.cb.b,b.cb,ja(c),b.B,m,z(b.Sb,b),z(b.Tb,b),!!d);(b=5E3*Math.pow(b.va,2))?window.setTimeout(a,b):a()}
function za(b,a){for(var c=0;c<a.length;c++)b.B[a[c]].oa&&i(Error("p`"+a[c]));for(var d=[],c=0;c<a.length;c++)d=d.concat(Aa(b,a[c]));la(d);return!b.Ta&&1<d.length?(c=d.shift(),b.b=Ba(d,function(a){return[a]}).concat(b.b),[c]):d}function Aa(b,a){for(var c=[a],d=ja(b.B[a].Xa);d.length;){var f=d.pop();b.B[f].oa||(c.unshift(f),Array.prototype.unshift.apply(d,b.B[f].Xa))}la(c);return c}function F(b,a){b.Da||(ta(b.B[a],z(b.Ya,b))&&Ca(b,4),ha(b.h,a),ha(b.f,a),0==b.f.length&&Da(b),wa(b))}
function G(b,a){b.g=b.B[a]}function H(b){!b.g||b.g.getId();b.g=m}function Ea(b,a){1<b.d.length?b.b=Ba(b.d,function(a){return[a]}).concat(b.b):Ca(b,a)}
function Ca(b,a){var c=b.d;b.f.length=0;for(var d=[],f=0;f<b.b.length;f++){var e=Fa(b.b[f],function(a){var b=Aa(this,a);return Ga(c,function(a){return 0<=B(b,a)})},b);ka(d,e)}for(f=0;f<c.length;f++)ga(d,c[f]);for(f=0;f<d.length;f++){for(e=0;e<b.b.length;e++)ha(b.b[e],d[f]);ha(b.h,d[f])}var g=b.n.error;if(g)for(f=0;f<g.length;f++)for(var h=g[f],e=0;e<d.length;e++)h("error",d[e],a);for(f=0;f<c.length;f++)b.B[c[f]]&&va(b.B[c[f]],a);b.d.length=0;wa(b)}
function Da(b){for(;b.b.length;){var a=Fa(b.b.shift(),function(a){return!this.B[a].oa},b);if(0<a.length){ya(b,a);return}}wa(b)}function xa(b,a){for(var c=b.n[a],d=0;c&&d<c.length;d++)c[d](a)}var t=this,ca="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36),da=0,I=Date.now||function(){return+new Date};var C=Array.prototype,B=C.indexOf?function(b,a,c){return C.indexOf.call(b,a,c)}:function(b,a,c){c=c==m?0:0>c?Math.max(0,b.length+c):c;if(x(b))return!x(a)||1!=a.length?-1:b.indexOf(a,c);for(;c<b.length;c++)if(c in b&&b[c]===a)return c;return-1},J=C.forEach?function(b,a,c){C.forEach.call(b,a,c)}:function(b,a,c){for(var d=b.length,f=x(b)?b.split(""):b,e=0;e<d;e++)e in f&&a.call(c,f[e],e,b)},Fa=C.filter?function(b,a,c){return C.filter.call(b,a,c)}:function(b,a,c){for(var d=b.length,f=[],e=0,g=x(b)?b.split(""):
b,h=0;h<d;h++)if(h in g){var j=g[h];a.call(c,j,h,b)&&(f[e++]=j)}return f},Ba=C.map?function(b,a,c){return C.map.call(b,a,c)}:function(b,a,c){for(var d=b.length,f=Array(d),e=x(b)?b.split(""):b,g=0;g<d;g++)g in e&&(f[g]=a.call(c,e[g],g,b));return f},Ga=C.some?function(b,a,c){return C.some.call(b,a,c)}:function(b,a,c){for(var d=b.length,f=x(b)?b.split(""):b,e=0;e<d;e++)if(e in f&&a.call(c,f[e],e,b))return l;return o},Ha=C.every?function(b,a,c){return C.every.call(b,a,c)}:function(b,a,c){for(var d=b.length,
f=x(b)?b.split(""):b,e=0;e<d;e++)if(e in f&&!a.call(c,f[e],e,b))return o;return l};var Ia="StopIteration"in t?t.StopIteration:Error("g");var Ja,Ka,Ma,Na;Na=Ma=Ka=Ja=o;var Oa;if(Oa=na()){var Pa=t.navigator;Ja=0==Oa.indexOf("Opera");Ka=!Ja&&-1!=Oa.indexOf("MSIE");Ma=!Ja&&-1!=Oa.indexOf("WebKit");Na=!Ja&&!Ma&&"Gecko"==Pa.product}var Qa=Ja,K=Ka,Ra=Na,Sa=Ma,Ta;
a:{var Ua="",Va;if(Qa&&t.opera)var Wa=t.opera.version,Ua="function"==typeof Wa?Wa():Wa;else if(Ra?Va=/rv\:([^\);]+)(\)|;)/:K?Va=/MSIE\s+([^\);]+)(\)|;)/:Sa&&(Va=/WebKit\/(\S+)/),Va)var Xa=Va.exec(na()),Ua=Xa?Xa[1]:"";if(K){var Ya,Za=t.document;Ya=Za?Za.documentMode:k;if(Ya>parseFloat(Ua)){Ta=""+Ya;break a}}Ta=Ua}var ab=Ta;D.prototype.Da=o;D.prototype.K=function $(){this.Da||(this.Da=l,this.u())};D.prototype.u=function $a(){this.vb&&pa.apply(m,this.vb)};/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
A(ra,D);A(sa,D);sa.prototype.h=ra;sa.prototype.oa=m;sa.prototype.getId=function $b(){return this.g};sa.prototype.u=function $c(){sa.M.u.call(this);oa(this.oa)};A(E,D);(function(b){b.i=function $d(){return b.Yb||(b.Yb=new b)}})(E);r=E.prototype;r.Ta=o;r.cb=m;r.va=0;r.bb=o;r.kb=o;r.dc=m;r.gc=function $e(a,c){if(x(a)){for(var d=a.split("/"),f=[],e=0;e<d.length;e++){var g=d[e].split(":"),h=g[0];if(g[1])for(var g=g[1].split(","),j=0;j<g.length;j++)g[j]=f[parseInt(g[j],36)];else g=[];f.push(h);this.B[h]=new sa(g,h)}c&&ka(this.f,c);this.g==this.k&&(this.g=m,ta(this.k,z(this.Ya,this))&&Ca(this,4))}};r.Ya=function $f(){return this.dc};
r.Sb=function $g(a){this.va++;401==a?(Ca(this,0),this.b.length=0):410==a?(Ea(this,3),Da(this)):3<=this.va?(Ea(this,1),Da(this)):ya(this,this.d,l,8001==a)};r.Tb=function $h(){Ea(this,2);Da(this)};r.u=function $i(){E.M.u.call(this);J(ma(this.B),oa);this.n=this.b=this.h=this.d=this.f=this.B=m};s("_DumpException",function(b){b.errsource=b.errsource||"plusone_publisher";i(b)},k);
var _ModuleManager_initialize=z(E.prototype.gc,E.i());
_ModuleManager_initialize('p1b/sy1/sy0:1/sy2/p1inl:2,1,3/sy4:2,1,3/p1p:5/p1p_test:5/p1inl_test:4,2,1,3/p1_manual_inline_test:4,2,3/sy7:1/p1_iframe_test_case:3,a/p1_inline_test_case:a',['sy1','sy0','sy2','sy4','p1p']);
}catch(e){_DumpException(e)}
try{
function bb(b){return b.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")}function cb(b){return"function"==aa(b)}function db(b){return eb[b]||(eb[b]=K&&document.documentMode&&document.documentMode>=b)}
function L(b){var a;if(!(a=fb[b])){a=0;for(var c=bb(""+ab).split("."),d=bb(""+b).split("."),f=Math.max(c.length,d.length),e=0;0==a&&e<f;e++){var g=c[e]||"",h=d[e]||"",j=RegExp("(\\d*)(\\D*)","g"),n=RegExp("(\\d*)(\\D*)","g");do{var p=j.exec(g)||["","",""],q=n.exec(h)||["","",""];if(0==p[0].length&&0==q[0].length)break;a=((0==p[1].length?0:parseInt(p[1],10))<(0==q[1].length?0:parseInt(q[1],10))?-1:(0==p[1].length?0:parseInt(p[1],10))>(0==q[1].length?0:parseInt(q[1],10))?1:0)||((0==p[2].length)<(0==
q[2].length)?-1:(0==p[2].length)>(0==q[2].length)?1:0)||(p[2]<q[2]?-1:p[2]>q[2]?1:0)}while(0==a)}a=fb[b]=0<=a}return a}var eb={},fb={};G(E.i(),"sy1");!K||db(9);!Ra&&!K||K&&db(9)||Ra&&L("1.9.1");K&&L("9");
F(E.i(),"sy1");H(E.i(),"sy1");
}catch(e){_DumpException(e)}
try{
function gb(b){return b.querySelectorAll&&b.querySelector&&(!Sa||"CSS1Compat"==document.compatMode||L("528"))}
function hb(b,a){var c,d,f,e;c=a||document;if(gb(c))c=c.querySelectorAll("."+b);else if(c.getElementsByClassName)c=c.getElementsByClassName(b);else if(c=a||document,gb(c)&&b)c=c.querySelectorAll(""+(b?"."+b:""));else if(b&&c.getElementsByClassName){var g=c.getElementsByClassName(b);c=g}else if(g=c.getElementsByTagName("*"),b){e={};for(d=f=0;c=g[d];d++){var h=c.className;"function"==typeof h.split&&0<=B(h.split(/\s+/),b)&&(e[f++]=c)}e.length=f;c=e}else c=g;return c}
function ib(b){var a=[],c=0,d;for(d in b)a[c++]=d;return a}function jb(b,a){return b===a}function kb(b){if("function"==typeof b.Q)return b.Q();if("function"!=typeof b.F){if(v(b)||x(b)){for(var a=[],b=b.length,c=0;c<b;c++)a.push(c);return a}return ib(b)}}function lb(b){if("function"==typeof b.F)return b.F();if(x(b))return b.split("");if(v(b)){for(var a=[],c=b.length,d=0;d<c;d++)a.push(b[d]);return a}return ma(b)}function mb(){}function nb(b){this.stack=Error().stack||"";b&&(this.message=""+b)}
function ob(){nb.call(this)}function pb(b,a){this.p={};this.b={};var c=arguments.length;if(1<c){c%2&&i(Error("k"));for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(b){b instanceof pb?(c=b.Q(),d=b.F()):(c=ib(b),d=ma(b));for(var f=0;f<c.length;f++)this.set(c[f],d[f])}}function qb(b,a){var c=a.substring(1);return b.b[a]?Number(c):c}function sb(b,a){for(var c=b.split("."),d=a||t,f;f=c.shift();)if(d[f]!=m)d=d[f];else return m;return d}function tb(b,a){this.width=b;this.height=a}
function ub(b,a){this.b=[];this.h=a||m}function vb(b,a,c){b.ia=l;b.d=c;b.ka=!a;wb(b)}function xb(b){b.ia&&(b.ib||i(new ob(b)),b.ib=o)}function yb(b,a,c,d){b.b.push([a,c,d]);b.ia&&wb(b);return b}function zb(b){return Ga(b.b,function(a){return cb(a[1])})}
function wb(b){b.f&&b.ia&&zb(b)&&(t.clearTimeout(b.f),delete b.f);b.g&&(b.g.Gb--,delete b.g);for(var a=b.d,c=o,d=o;b.b.length&&0==b.pa;){var f=b.b.shift(),e=f[0],g=f[1],f=f[2];if(e=b.ka?g:e)try{var h=e.call(f||b.h,a);h!==k&&(b.ka=b.ka&&(h==a||h instanceof Error),b.d=a=h);a instanceof ub&&(d=l,b.pa++)}catch(j){a=j,b.ka=l,zb(b)||(c=l)}}b.d=a;d&&b.pa&&(yb(a,z(b.Va,b,l),z(b.Va,b,o)),a.Ib=l);c&&(b.f=t.setTimeout(function(){i(a)},0))}
function Ab(b,a,c){if("function"==typeof b.forEach)b.forEach(a,c);else if(v(b)||x(b))J(b,a,c);else for(var d=kb(b),f=lb(b),e=f.length,g=0;g<e;g++)a.call(c,f[g],d&&d[g],b)}function Bb(b,a){for(var c,d,f=1;f<arguments.length;f++){d=arguments[f];for(c in d)b[c]=d[c];for(var e=0;e<Cb.length;e++)c=Cb[e],Object.prototype.hasOwnProperty.call(d,c)&&(b[c]=d[c])}}function Db(b){var a=aa(b);if("object"==a||"array"==a){if(b.J)return b.J();var a="array"==a?[]:{},c;for(c in b)a[c]=Db(b[c]);return a}return b}
function Eb(b,a,c){for(var d in b)a.call(c,b[d],d,b)}function Fb(b){Fb[" "](b);return b}function M(b,a){this.type=b;this.b=this.target=a}function Gb(b,a){b&&this.init(b,a)}function Hb(){}
function Ib(b,a,c,d,f){if(a){if(u(a)){for(var e=0;e<a.length;e++)Ib(b,a[e],c,d,f);return m}var d=!!d,g=N;a in g||(g[a]={l:0,C:0});g=g[a];d in g||(g[d]={l:0,C:0},g.l++);var g=g[d],h=ba(b),j;g.C++;if(g[h]){j=g[h];for(e=0;e<j.length;e++)if(g=j[e],g.ma==c&&g.Ha==f){if(g.fa)break;return j[e].key}}else j=g[h]=[],g.l++;e=Jb();e.src=b;g=new Hb;g.init(c,e,b,a,d,f);c=g.key;e.key=c;j.push(g);Kb[c]=g;O[h]||(O[h]=[]);O[h].push(g);b.addEventListener?(b==t||!b.Wa)&&b.addEventListener(a,e,d):b.attachEvent(a in Lb?
Lb[a]:Lb[a]="on"+a,e);return c}i(Error("t"))}function Jb(){var b=Mb,a=Nb?function(c){return b.call(a.src,a.key,c)}:function(c){c=b.call(a.src,a.key,c);if(!c)return c};return a}function Ob(b,a,c,d,f){if(u(a)){for(var e=0;e<a.length;e++)Ob(b,a[e],c,d,f);return m}d=!!d;a:{e=N;if(a in e&&(e=e[a],d in e&&(e=e[d],b=ba(b),e[b]))){b=e[b];break a}b=m}if(!b)return o;for(e=0;e<b.length;e++)if(b[e].ma==c&&b[e].capture==d&&b[e].Ha==f)return Pb(b[e].key);return o}
function Pb(b){if(!Kb[b])return o;var a=Kb[b];if(a.fa)return o;var c=a.src,d=a.type,f=a.d,e=a.capture;c.removeEventListener?(c==t||!c.Wa)&&c.removeEventListener(d,f,e):c.detachEvent&&c.detachEvent(d in Lb?Lb[d]:Lb[d]="on"+d,f);c=ba(c);f=N[d][e][c];if(O[c]){var g=O[c];ha(g,a);0==g.length&&delete O[c]}a.fa=l;f.eb=l;Qb(d,e,c,f);delete Kb[b];return l}
function Qb(b,a,c,d){if(!d.za&&d.eb){for(var f=0,e=0;f<d.length;f++)d[f].fa?d[f].d.src=m:(f!=e&&(d[e]=d[f]),e++);d.length=e;d.eb=o;0==e&&(delete N[b][a][c],N[b][a].l--,0==N[b][a].l&&(delete N[b][a],N[b].l--),0==N[b].l&&delete N[b])}}
function Rb(b,a,c){var d=0,f=b==m,e=a==m,g=c==m,c=!!c;if(f)Eb(O,function(b){for(var f=b.length-1;0<=f;f--){var h=b[f];if((e||a==h.type)&&(g||c==h.capture))Pb(h.key),d++}});else if(b=ba(b),O[b]){b=O[b];for(f=b.length-1;0<=f;f--){var h=b[f];if((e||a==h.type)&&(g||c==h.capture))Pb(h.key),d++}}return d}
function Sb(b,a,c,d,f){var e=1,a=ba(a);if(b[a]){b.C--;b=b[a];b.za?b.za++:b.za=1;try{for(var g=b.length,h=0;h<g;h++){var j=b[h];j&&!j.fa&&(e&=Tb(j,f)!==o)}}finally{b.za--,Qb(c,d,a,b)}}return Boolean(e)}function Tb(b,a){var c=b.handleEvent(a);b.Ua&&Pb(b.key);return c}
function Mb(b,a){if(!Kb[b])return l;var c=Kb[b],d=c.type,f=N;if(!(d in f))return l;var f=f[d],e,g;if(!Nb){e=a||sb("window.event");var h=l in f,j=o in f;if(h){if(0>e.keyCode||e.returnValue!=k)return l;a:{var n=o;if(0==e.keyCode)try{e.keyCode=-1;break a}catch(p){n=l}if(n||e.returnValue==k)e.returnValue=l}}n=new Gb;n.init(e,this);e=l;try{if(h){for(var q=[],y=n.b;y;y=y.parentNode)q.push(y);g=f[l];g.C=g.l;for(var w=q.length-1;!n.d&&0<=w&&g.C;w--)n.b=q[w],e&=Sb(g,q[w],d,l,n);if(j){g=f[o];g.C=g.l;for(w=
0;!n.d&&w<q.length&&g.C;w++)n.b=q[w],e&=Sb(g,q[w],d,o,n)}}else e=Tb(c,n)}finally{q&&(q.length=0),n.K()}return e}d=new Gb(a,this);try{e=Tb(c,d)}finally{d.K()}return e}function Ub(b){this.b=b}function Vb(b){this.b=b}function Wb(b){this.b=b}function Xb(b){this.b=b}function Yb(b){this.b=b}function Zb(){}function ac(b,a){this.d=b||m;this.T=a||m;this.b=1}function bc(b,a,c){if(!c||c==b.b)b.T=a,b.b++,b.dispatchEvent("change")}
function cc(b,a,c){!c||c==b.b?(b.T=m,b.b++,b.d=a,b.dispatchEvent("change")):(b.d=a,b.T||b.dispatchEvent("change"))}function dc(){this.d=[]}function ec(b,a){if(!(1<=b.b))return a(),0;return!(1<=b.d.length)?(b.d.push(a),1):2}function fc(b){this.d={};this.f={};this.b=(b||window.googleapis).plusones}function gc(b,a){b.f[a]||(b.f[a]=new dc);return b.f[a]}function hc(b,a){a.transport={name:"wrapped_googleapis",execute:z(b.ic,b,a.transport)};return a}
function ic(b,a){switch(a.method){case "pos.plusones.get":return new Xb(b);case "pos.plusones.insert":return new Yb(b);case "pos.plusones.delete":return new Wb(b);default:return new Ub(b)}}function jc(b,a){var c=a.method,d=a.params,d=d&&d.id;return("pos.plusones.insert"==c||"pos.plusones.delete"==c)&&d?gc(b,d):m}
function kc(b,a,c){a||(a={});var d=c||window,c="undefined"!=typeof b.href?b.href:""+b,b=a.target||b.target,f=[],e;for(e in a)switch(e){case "width":case "height":case "top":case "left":f.push(e+"="+a[e]);break;case "target":case "noreferrer":break;default:f.push(e+"="+(a[e]?1:0))}e=f.join(",");if(a.noreferrer){if(a=d.open("",b,e))K&&-1!=c.indexOf(";")&&(c="'"+c.replace(/'/g,"%27")+"'"),a.opener=m,Sa?a.location.href=c:(lc.test(c)&&(-1!=c.indexOf("&")&&(c=c.replace(mc,"&amp;")),-1!=c.indexOf("<")&&
(c=c.replace(nc,"&lt;")),-1!=c.indexOf(">")&&(c=c.replace(oc,"&gt;")),-1!=c.indexOf('"')&&(c=c.replace(pc,"&quot;"))),a.document.write('<META HTTP-EQUIV="refresh" content="0; url='+c+'">'),a.document.close())}else a=d.open(c,b,e);return a}function qc(){this.b={}}
function rc(b,a,c,d){b=b||window;"number"!=typeof c&&(c=800);"number"!=typeof d&&(d=600);var f=b.outerHeight!=m?b.outerHeight:b.document.documentElement.clientHeight,e=b.screenY!=m?b.screenY:b.screenTop,b=Math.max(0,(b.screenX!=m?b.screenX:b.screenLeft)+((b.outerWidth!=m?b.outerWidth:b.document.documentElement.clientWidth)>>1)-(c>>1)),f=Math.max(0,e+(f>>1)-(d>>1)),c={left:b,top:f,menubar:o,toolbar:o,location:o,status:l,scrollbars:l,width:c,height:d};a&&(c.target=a);return c}
function sc(b,a){this.z=b;this.I="GooglePlusOneSignup";this.h="";this.H=""+Math.floor(1E9*Math.random());this.k=window.location.protocol+"//"+window.location.host;this.d=m;this.f=new ub;this.w=a;this.q=new tb(890,650)}function tc(b,a){a.match(/.*\/$/)&&(a=a.substr(0,a.length-1));b.h=a}function uc(b){return window.localStorage&&window.localStorage.ihatepopups?l:b.b}
function vc(b,a){var c=b.h+"/_/+1/messageproxy";if(!b.n){var d=document.createElement("div");d.style.position="absolute";d.style.left="-1000px";d.style.top="-1000px";d.style.width="1px";d.style.height="1px";document.body.appendChild(d);b.n=iframes.open(c,{container:d},{},{handleMessage:z(b.G,b)})}(c=kc(b.h+"/+1/profile/?type=po&client="+b.w+"&gpsrc="+encodeURIComponent(b.z)+"&parent="+encodeURIComponent(b.k)+"&proxy="+b.n.getId()+(!window.__P1_LOCALE?"":"&hl="+window.__P1_LOCALE)+"#"+b.H,rc(a,b.I,
b.q.width,b.q.height)))&&c.focus();return c}function wc(b){return kc("https://www.google.com/support/profiles/?p=plusone_button_error&hl=en-US",rc(b||window,"GooglePlusOneHelp",800,600))}function P(b){this.xb=b;this.Ea=[]}mb.prototype.next=function $j(){i(Ia)};mb.prototype.ha=function $k(){return this};A(nb,Error);nb.prototype.name="CustomError";A(ob,nb);ob.prototype.message="Already called";r=pb.prototype;r.l=0;r.ra=0;r.L=function $l(){return this.l};
r.F=function $m(){var a=[],c;for(c in this.p)":"==c.charAt(0)&&a.push(this.p[c]);return a};r.Q=function $n(){var a=[],c;for(c in this.p)":"==c.charAt(0)&&a.push(qb(this,c));return a};r.D=function $o(a){return":"+a in this.p};r.wa=function $p(a){for(var c in this.p)if(":"==c.charAt(0)&&this.p[c]==a)return l;return o};r.Ga=function $q(a,c){if(this===a)return l;if(this.l!=a.L())return o;var d=c||jb,f;for(f in this.p)if(f=qb(this,f),!d(this.get(f),a.get(f)))return o;return l};
r.clear=function $r(){this.p={};this.ra=this.l=0;this.b={}};r.remove=function $s(a){var a=":"+a,c=this.p,d;(d=a in c)&&delete c[a];return d?(delete this.b[a],this.l--,this.ra++,l):o};r.get=function $t(a,c){var d=":"+a;return d in this.p?this.p[d]:c};r.set=function $u(a,c){var d=":"+a;d in this.p||(this.ra++,this.l++,"number"==typeof a&&(this.b[d]=l));this.p[d]=c};r.J=function $v(){return new pb(this)};
r.ha=function $x(a){var c=0,d=this.Q(),f=this.p,e=this.ra,g=this,h=new mb;h.next=function $w(){for(;;){e!=g.ra&&i(Error("l"));c>=d.length&&i(Ia);var h=d[c++];return a?h:f[":"+h]}};return h};var Cb="constructor,hasOwnProperty,isPrototypeOf,propertyIsEnumerable,toLocaleString,toString,valueOf".split(","),lc=/[&<>\"]/,pc=/\"/g,oc=/>/g,nc=/</g,mc=/&/g;tb.prototype.J=function $y(){return new tb(this.width,this.height)};
tb.prototype.floor=function $z(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};tb.prototype.round=function $A(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};r=ub.prototype;r.ia=o;r.ka=o;r.pa=0;r.ib=o;r.Ib=o;r.Gb=0;r.Va=function $B(a,c){vb(this,a,c);this.pa--;0==this.pa&&this.ia&&wb(this)};r.aa=function $C(a){xb(this);vb(this,l,a)};G(E.i(),"sy0");Fb[" "]=function $D(){};!K||db(9);var Nb=!K||db(9);K&&L("8");!Sa||L("528");Ra&&L("1.9b")||K&&L("8")||Qa&&L("9.5")||Sa&&L("528");!Ra||L("8");A(M,D);M.prototype.u=function $E(){delete this.type;delete this.target;delete this.b};M.prototype.d=o;M.prototype.f=l;A(Gb,M);r=Gb.prototype;r.target=m;r.relatedTarget=m;r.clientX=0;r.clientY=0;r.button=0;
r.init=function $F(a,c){var d=this.type=a.type;M.call(this,d);this.target=a.target||a.srcElement;this.b=c;var f=a.relatedTarget;if(f){if(Ra){var e;a:{try{Fb(f.nodeName);e=l;break a}catch(g){}e=o}e||(f=m)}}else"mouseover"==d?f=a.fromElement:"mouseout"==d&&(f=a.toElement);this.relatedTarget=f;this.clientX=a.clientX!==k?a.clientX:a.pageX;this.clientY=a.clientY!==k?a.clientY:a.pageY;this.button=a.button;this.state=a.state;delete this.f;delete this.d};
r.u=function $G(){Gb.M.u.call(this);this.relatedTarget=this.b=this.target=m};var xc=0;r=Hb.prototype;r.key=0;r.fa=o;r.Ua=o;r.init=function $H(a,c,d,f,e,g){cb(a)?this.b=l:a&&a.handleEvent&&cb(a.handleEvent)?this.b=o:i(Error("s"));this.ma=a;this.d=c;this.src=d;this.type=f;this.capture=!!e;this.Ha=g;this.Ua=o;this.key=++xc;this.fa=o};r.handleEvent=function $I(a){return this.b?this.ma.call(this.Ha||this.src,a):this.ma.handleEvent.call(this.ma,a)};var Kb={},N={},O={},Lb={};Ub.prototype.f=function $J(a){return a};Ub.prototype.g=function $K(a){return a};Ub.prototype.d=0;Ub.prototype.update=function $L(a,c){var d=this.b.v(a);!c||c.error||!c.result?bc(d,m,this.d):cc(d,c.result,this.d)};A(Vb,Ub);Vb.prototype.f=function $M(a){var c=a.params,d=c&&c.optimistic,f=c&&c.id;this.n=f;var e=this.b.v(f).get(),g=e=e?Db(e):{id:f,isSetByViewer:o,metadata:{}},g=g||{};g.metadata=g.metadata||{};g.metadata.globalCounts=g.metadata.globalCounts||{};this.h(e,c);this.k=e;d&&(bc(this.b.v(f),e),a=Db(a),delete a.params.optimistic);this.d=this.b.v(f).b;return a};
Vb.prototype.g=function $N(a){if(a.result){var c=a.result,d=this.k;c.metadata=c.metadata||d.metadata;c.metadata.globalCounts=c.metadata.globalCounts||d.metadata.globalCounts;c.metadata.globalCounts.count=c.metadata.globalCounts.count||d.metadata.globalCounts.count;if(d=c.metadata.globalCounts.person||d.metadata.globalCounts.person)c.metadata.globalCounts.person=d}this.update(this.n,a);return a};A(Wb,Vb);Wb.prototype.h=function $O(a){a.isSetByViewer&&a.metadata.globalCounts.count!=k&&(a.metadata.globalCounts.count=Math.max(a.metadata.globalCounts.count-1,0));a.isSetByViewer=o};A(Xb,Ub);Xb.prototype.f=function $P(a){this.h=a.params&&a.params.id;this.d=this.b.v(this.h).b;return a};Xb.prototype.g=function $Q(a){this.update(this.h,a);return a};A(Yb,Vb);Yb.prototype.h=function $R(a,c){!a.isSetByViewer&&a.metadata.globalCounts.count!=k&&a.metadata.globalCounts.count++;a.isSetByViewer=l;a.aclJson=c.aclJson};A(Zb,D);r=Zb.prototype;r.Wa=l;r.Ja=m;r.addEventListener=function $S(a,c,d,f){Ib(this,a,c,d,f)};r.removeEventListener=function $T(a,c,d,f){Ob(this,a,c,d,f)};
r.dispatchEvent=function $U(a){var c=a.type||a,d=N;if(c in d){if(x(a))a=new M(a,this);else if(a instanceof M)a.target=a.target||this;else{var f=a,a=new M(c,this);Bb(a,f)}var f=1,e,d=d[c],c=l in d,g;if(c){e=[];for(g=this;g;g=g.Ja)e.push(g);g=d[l];g.C=g.l;for(var h=e.length-1;!a.d&&0<=h&&g.C;h--)a.b=e[h],f&=Sb(g,e[h],a.type,l,a)&&a.f!=o}if(o in d)if(g=d[o],g.C=g.l,c)for(h=0;!a.d&&h<e.length&&g.C;h++)a.b=e[h],f&=Sb(g,e[h],a.type,o,a)&&a.f!=o;else for(e=this;!a.d&&e&&g.C;e=e.Ja)a.b=e,f&=Sb(g,e,a.type,
o,a)&&a.f!=o;a=Boolean(f)}else a=l;return a};r.u=function $V(){Zb.M.u.call(this);Rb(this);this.Ja=m};A(ac,Zb);ac.prototype.get=function $W(){return this.T||this.d};dc.prototype.b=0;r=fc.prototype;r.get=function $X(a){return hc(this,this.b.get(a))};r.remove=function $Y(a){return hc(this,this.b.remove(a))};r.v=function $Z(a){this.d[a]||(this.d[a]=new ac);return this.d[a]};r.X=function $_(a,c){var d=a.id;return Ib(this.v(d),"change",z(function(){var a=this.v(d);c(a.get(),!a.T)},this))};
r.ic=function $0(a,c,d){for(var f={},e=[],g=[],h=0,j=c.length;h<j;++h){var n=c[h],p=jc(this,n);p&&(p.b++,g.push(p));p=n.id;f[p]=ic(this,n);(n=f[p].f(n))&&e.push(n)}a.execute(e,z(function(a){for(var c=0,e=g.length;c<e;++c){var h=g[c];for(h.b--;!(1<=h.b)&&h.d.length;)h.d.shift()()}var c={},j;for(j in f)(e=f[j].g(a[j]||m))&&(c[j]=e);d(c)},this))};sc.prototype.G=function $1(a){try{var c=new qc;c.b=Object(a);this.b=!!c.b.created;this.g=""+(c.b.version||"");this.f.aa(c)}catch(d){if(this.d)try{this.d(d)}catch(f){}a=this.f;xb(a);vb(a,o,d)}};A(P,D);var yc=[];P.prototype.X=function $2(a,c,d,f,e){u(c)||(yc[0]=c,c=yc);for(var g=0;g<c.length;g++)this.Ea.push(Ib(a,c[g],d||this,f||o,e||this.xb||this));return this};P.prototype.u=function $3(){P.M.u.call(this);J(this.Ea,Pb);this.Ea.length=0};P.prototype.handleEvent=function $4(){i(Error("u"))};
F(E.i(),"sy0");H(E.i(),"sy0");
}catch(e){_DumpException(e)}
try{
function zc(b){b=""+b;return!Ac.test(b)?encodeURIComponent(b):b}function Bc(b){if(b[1]){var a=b[0],c=a.indexOf("#");0<=c&&(b.push(a.substr(c)),b[0]=a=a.substr(0,c));c=a.indexOf("?");0>c?b[1]="?":c==a.length-1&&(b[1]=k)}return b.join("")}function Cc(b,a,c){if(u(a))for(var d=0;d<a.length;d++)c.push("&",b),""!==a[d]&&c.push("=",zc(a[d]));else a!=m&&(c.push("&",b),""!==a&&c.push("=",zc(a)))}function Dc(b,a){for(var c in a)Cc(c,a[c],b);return b}var Ac=/^[a-zA-Z0-9\-_.!~*'()]*$/;G(E.i(),"sy2");var Ec=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([\\w\\d\\-\\u0100-\\uffff.%]*)(?::([0-9]+))?)?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$");
F(E.i(),"sy2");H(E.i(),"sy2");
}catch(e){_DumpException(e)}
try{
function R(b){return b.parentWindow||b.defaultView}function gd(b){if(hd[b])return hd[b];b=""+b;if(!hd[b]){var a=/function ([^\(]+)/.exec(b);hd[b]=a?a[1]:"[Anonymous]"}return hd[b]}function id(b,a,c){for(c=c||0;c<a.length;c+=2)Cc(a[c],a[c+1],b);return b}function jd(b){this.b=b||t.document||document}function kd(b,a){return x(a)?b.b.getElementById(a):a}function ld(b){return 9==b.nodeType?b:b.ownerDocument||b.document}
function md(b,a){var c=[];if(0<=B(a,b))c.push("[...circular reference...]");else if(b&&50>a.length){c.push(gd(b)+"(");for(var d=b.arguments,f=0;f<d.length;f++){0<f&&c.push(", ");var e;e=d[f];switch(typeof e){case "object":e=e?"object":"null";break;case "string":break;case "number":e=""+e;break;case "boolean":e=e?"true":"false";break;case "function":e=(e=gd(e))?e:"[fn]";break;default:e=typeof e}40<e.length&&(e=e.substr(0,40)+"...");c.push(e)}a.push(b);c.push(")\n");try{c.push(md(b.caller,a))}catch(g){c.push("[exception trying to get caller]\n")}}else b?
c.push("[...long stack...]"):c.push("[end]");return c.join("")}function od(b){var a=typeof b;return"object"==a&&b||"function"==a?"o"+ba(b):a.substr(0,1)+b}function pd(b,a,c){if("function"==typeof b.every)return b.every(a,c);if(v(b)||x(b))return Ha(b,a,c);for(var d=kb(b),f=lb(b),e=f.length,g=0;g<e;g++)if(!a.call(c,f[g],d&&d[g],b))return o;return l}function qd(b){if("function"==typeof b.L)b=b.L();else if(v(b)||x(b))b=b.length;else{var a=0,c;for(c in b)a++;b=a}return b}
function rd(b){if(b instanceof mb)return b;if("function"==typeof b.ha)return b.ha(o);if(v(b)){var a=0,c=new mb;c.next=function $ea(){for(;;){a>=b.length&&i(Ia);if(a in b)return b[a++];a++}};return c}i(Error("h"))}function sd(b,a){return Bc(2==arguments.length?id([b],arguments[1],0):id([b],arguments,1))}function td(){}function ud(b){return b.b}function vd(b,a){function c(){}c.prototype=b.prototype;var d=new c;b.apply(d,Array.prototype.slice.call(arguments,1));return d}
function wd(b){return md(b||arguments.callee.caller,[])}function xd(b){this.p=new pb;if(b)for(var b=lb(b),a=b.length,c=0;c<a;c++)yd(this,b[c])}function yd(b,a){b.p.set(od(a),a)}function zd(b,a){var c=qd(a);if(b.L()>c)return o;!(a instanceof xd)&&5<c&&(a=new xd(a));return pd(b,function(b){if("function"==typeof a.contains)b=a.contains(b);else if("function"==typeof a.wa)b=a.wa(b);else if(v(a)||x(a))b=0<=B(a,b);else a:{for(var c in a)if(a[c]==b){b=l;break a}b=o}return b})}
function Ad(b){var a={},c;for(c in b)a[c]=b[c];return a}function Bd(b,a,c){for(var d=x(b)?b.split(""):b,f=b.length-1;0<=f;--f)f in d&&a.call(c,d[f],f,b)}function Cd(b,a){var c=Array.prototype.slice.call(arguments,1);return function(){var a=Array.prototype.slice.call(arguments);a.unshift.apply(a,c);return b.apply(this,a)}}function Dd(b){this.b=b||[]}function Ed(b){var a=[];J(b.split(","),function(b){if((b=bb(b).toLowerCase())&&!(0<=B(a,b)))0<=B(Fd,b)||i(Error("B`"+b)),a.push(b)});return a}
function Gd(b,a){this.d=b;this.b=a}function Hd(b,a){if(iframer){var c=iframer[a];c&&c({type:b.d,id:b.b})}}
function Id(b,a,c,d,f,e,g,h,j){this.k=new Gd(b,g);a:{var b=(ld(c)?R(ld(c)):window).location.pathname,n=/^(\/u\/\d+)\//;if(0==a.lastIndexOf("/",0)&&!a.match(n)&&(b=b.match(n))){a=b[1]+a;break a}}this.q=a;this.h={style:"bubble",bubbletype:"pls-default",arrowPosition:"center",anchorPosition:"center",closeClickDetection:l,anchor:c,width:d};this.f={hl:"en-US",url:g,t:h};j&&(this.f.source=j);window.external&&window.external.GTB_IsToolbar&&(this.f.inlineRecipientSuggestions=l);document.documentMode&&(this.f.hostiemode=
document.documentMode);this.g={mouseEvent:f,trackingEvent:e};iframer&&iframer.onshare&&(this.g.onshare=iframer.onshare)}function Jd(b,a){b.f.referer=a;return b}function Kd(b,a){b.h.expandTo=a;return b}function Ld(b,a,c,d,f,e){Id.call(this,"confirm","/_/+1/confirm",b,450,a,c,d,f,e)}function Md(b){this.b=b||[];this.b[0]=this.b[0]||[]}function Nd(){this.b=[]}function Od(b){var a=new Md,b=(b=b.b)||[];a.b[0]=[];for(var c=0;c<b.length;c++)a.b[0][c]=b[c].b;return a}
function Pd(b){var a=Qd(b,"la");a||(a=new Nd,S(b,"la",a));return a}function Rd(b,a,c,d,f,e,g){Id.call(this,"hover","/_/+1/hover",b,f?450:350,a,c,d,e,g);this.f.isSet=f}function Sd(b,a,c){this.k=!!a.si;this.n=!!a.su;this.z=a.e||m;this.w=a.dn||m;this.f=a.a||m;this.h=a.at||m;var d=a.ld;d&&Pd(b).b.push(new Dd(d));this.q={id:a.id,isSetByViewer:!!a.is,metadata:{globalCounts:{count:a.c||0}}};this.g=c||{};this.b=a.s||"widget";this.d=a.r||m}
function Td(b){var a=Qd(b,"ea");a||(a=new fc,S(b,"ea",a));return a}function Ud(b){this.d={};this.k={};this.g={};this.b={};this.n={};this.q=b?b.q:new Zb;this.z=!b;this.f=m;b?(this.f=b,this.g=b.g,this.b=b.b,this.k=b.k,this.n=b.n):I();b=Vd(this);this!=b&&(b.h?b.h.push(this):b.h=[this])}function Vd(b){for(;b.f;)b=b.f;return b}function Wd(b,a){for(var c=b;c;){if(c==a)return l;c=c.f}return o}function Qd(b,a){for(var c=b;c;c=c.f)if(c.d[a])return c.d[a][0];return(c=b.g[a])?(c=c(b),S(b,a,c),c):m}
function S(b,a,c,d){b.d[a]=[c,!d];c=Xd(b,b,a);for(d=0;d<c.length;d++)c[d].aa(m);delete b.k[a]}function Yd(b,a){if(b.S!=a.S){if(Wd(b.S,a.S))return 1;if(Wd(a.S,b.S))return-1}return b.index<a.index?-1:b.index==a.index?0:1}function Xd(b,a,c){var d=[],f=b.b[c];f&&(Bd(f,function(b){Wd(b.S,a)&&(d.push(b.Lb),ha(f,b))}),0==f.length&&delete b.b[c]);return d}function Zd(b,a){b.b&&Ab(b.b,function(b,d,f){Bd(b,function(d){d.S==a&&ha(b,d)});0==b.length&&delete f[d]})}
function ae(b){nb.call(this);this.id=b;this.message='Service for "'+b+'" is not registered'}
function be(){function b(a){if(!a.lc){a.lc=l;if(a.ca){var c=a.ca,d=b;if(v(c))try{J(c,d,k)}catch(e){e!==Ia&&i(e)}else{c=rd(c);try{for(;;)d.call(k,c.next(),k,c)}catch(f){f!==Ia&&i(f)}}}h.push(a)}}var a={},c,d;for(c=T.length-1;0<=c;--c){var f=T[c];if(f.na.b){var e=f.na.b;for(d=e.length-1;0<=d;--d)a[e[d].id]=f}if(f.na.h){e=f.na.h;for(d=e.length-1;0<=d;--d)a[e[d].id]=f}}for(c=T.length-1;0<=c;--c){f=T[c];e=f.na;if(e.d){f.ca=new xd;for(d=e.d.length-1;0<=d;--d){var g=a[e.d[d]];g&&yd(f.ca,g)}}if(e.f){f.ca||
(f.ca=new xd);for(d=e.f.length-1;0<=d;--d)(g=a[e.f[d]])&&yd(f.ca,g)}}var h=[];J(T,b);T=h}
function ce(b,a,c){this.d=a||U.pb;this.ga=c||0;this.h=40;this.b=1;this.G=3;this.k=this.f=0;this.Z=o;this.I=this.H="";this.n="-";this.q="";this.g=1;this.z=3;this.w=this.Y=o;if("number"==typeof b)switch(b){case 1:de(this,U.nb);break;case 2:de(this,U.Fb);break;case 3:de(this,U.Ab);break;case 4:b=U.mb;a=["0"];c=ee[this.d][0]&7;if(0<c){a.push(".");for(var d=0;d<c;d++)a.push("0")}b=b.replace(/0.00/g,a.join(""));de(this,b);break;default:i(Error("E"))}else de(this,b)}
function de(b,a){a.replace(/ /g,"\u00a0");var c=[0];b.H=fe(b,a,c);for(var d=c[0],f=-1,e=0,g=0,h=0,j=-1,n=a.length,p=l;c[0]<n&&p;c[0]++)switch(a.charAt(c[0])){case "#":0<g?h++:e++;0<=j&&0>f&&j++;break;case "0":0<h&&i(Error("G`"+a));g++;0<=j&&0>f&&j++;break;case ",":j=0;break;case ".":0<=f&&i(Error("H`"+a));f=e+g+h;break;case "E":b.w&&i(Error("I`"+a));b.w=l;b.k=0;c[0]+1<n&&"+"==a.charAt(c[0]+1)&&(c[0]++,b.Z=l);for(;c[0]+1<n&&"0"==a.charAt(c[0]+1);)c[0]++,b.k++;(1>e+g||1>b.k)&&i(Error("J`"+a));p=o;break;
default:c[0]--,p=o}0==g&&0<e&&0<=f&&(g=f,0==g&&g++,h=e-g,e=g-1,g=1);(0>f&&0<h||0<=f&&(f<e||f>e+g)||0==j)&&i(Error("K`"+a));h=e+g+h;b.G=0<=f?h-f:0;0<=f&&(b.f=e+g-f,0>b.f&&(b.f=0));b.b=(0<=f?f:h)-e;b.w&&(b.h=e+b.b,0==b.G&&0==b.b&&(b.b=1));b.z=Math.max(0,j);b.Y=0==f||f==h;d=c[0]-d;b.I=fe(b,a,c);c[0]<a.length&&";"==a.charAt(c[0])?(c[0]++,b.n=fe(b,a,c),c[0]+=d,b.q=fe(b,a,c)):(b.n=b.H+b.n,b.q+=b.I)}
function he(b,a,c,d){for(var f=Math.pow(10,b.G),a=Math.round(a*f),e=Math.floor(a/f),g=Math.floor(a-e*f),h=0<b.f||0<g,j="",a=e;1.0E20<a;)j="0"+j,a=Math.round(a/10);var j=a+j,n=U.ob,p=U.rb,a=U.ta.charCodeAt(0),q=j.length;if(0<e||0<c){for(e=q;e<c;e++)d.push(U.ta);for(e=0;e<q;e++)d.push(String.fromCharCode(a+1*j.charAt(e))),1<q-e&&0<b.z&&1==(q-e)%b.z&&d.push(p)}else h||d.push(U.ta);(b.Y||h)&&d.push(n);c=""+(g+f);for(f=c.length;"0"==c.charAt(f-1)&&f>b.f+1;)f--;for(e=1;e<f;e++)d.push(String.fromCharCode(a+
1*c.charAt(e)))}function ie(b,a,c){c.push(U.qb);0>a?(a=-a,c.push(U.ub)):b.Z&&c.push(U.Cb);for(var a=""+a,d=a.length;d<b.k;d++)c.push(U.ta);c.push(a)}
function fe(b,a,c){for(var d="",f=o,e=a.length;c[0]<e;c[0]++){var g=a.charAt(c[0]);if("'"==g)c[0]+1<e&&"'"==a.charAt(c[0]+1)?(c[0]++,d+="'"):f=!f;else if(f)d+=g;else switch(g){case "#":case "0":case ",":case ".":case ";":return d;case "\u00a4":if(c[0]+1<e&&"\u00a4"==a.charAt(c[0]+1))c[0]++,d+=b.d;else switch(b.ga){case 0:d+=ee[b.d][1];break;case 2:var g=b.d,h=ee[g],d=d+(g==h[1]?g:g+" "+h[1]);break;case 1:d+=ee[b.d][2]}break;case "%":1!=b.g&&i(Error("F"));b.g=100;d+=U.zb;break;case "\u2030":1!=b.g&&
i(Error("F"));b.g=1E3;d+=U.Bb;break;default:d+=g}}return d}function je(b){this.b=b}function ke(b){for(var b=(b.b.cookie||"").split(le),a=[],c=[],d,f,e=0;f=b[e];e++)d=f.indexOf("="),-1==d?(a.push(""),c.push(f)):(a.push(f.substring(0,d)),c.push(f.substring(d+1)));return{keys:a,lb:c}}function V(b,a){this.d=me?[]:"";b!=m&&this.b.apply(this,arguments)}function W(b){return"object"===typeof b&&b&&0===b.sc?b.content:(""+b).replace(ne,oe)}function oe(b){return pe[b]}
function qe(b,a){var c=a||new V;if(9<b.P)c.b("Lots of people +1'd this");else if(6<b.P){var d=W(b.count)+" million people +1'd this";c.b(d)}else 3<b.P?(d=W(b.count)+" thousand people +1'd this",c.b(d)):1==b.count?c.b("1 person +1'd this"):(d=W(b.count)+" people +1'd this",c.b(d));return a?"":c.toString()}function re(){}function se(){}function te(b){this.b=b}
function ue(b){P.call(this);var a=gadgets.util.getUrlParameters()||{};this.Oa=a.expandTo?Ed(a.expandTo):[];this.w=a;var c=Qd(b,"fa");this.Nb=z(c.ab,c);this.d=c=b.get("ia");this.yb=a.ad;var d=a.width,f=a.annotation;"only"==f||"inline"==f?0==d?d=450:120>d&&(d=120):"pp"==f&&(d=180);this.Eb=d;this.Sa=!(a.db&&"1"==a.db);this.b=Td(b);this.g=a=b.get("ka");var e=a.q;this.f=d=e.id;var g=this.b.v(d);if(g&&(this.X(g,"change",this.Aa),this.H=I(),this.tb=b.get("ha"),f=R(c.b),this.h=b.get("ga"),this.Db=new ce(1),
this.k=c=kd(c||ve||(ve=new jd),"button"),cc(g,e),this.Pa=Pd(b),this.I=a.k,this.h.b=a.n,yb(this.h.f,this.ec,m,this),b=a.w,this.Na=a.z||"",this.Ma=b||"",we(this,this.b.v(d).get()),this.Qa=I(),this.X(f,"unload",this.K),this.X(c,"click",this.Za),(b=xe(this))&&this.k.setAttribute("title",""),b||ye(this)))this.X(c,"mouseover",this.Vb),this.X(c,"mouseout",this.Ub)}
function ze(b){b=b||new Ud;if(!Ae){be();for(var a=0;a<T.length;++a){var c=T[a].na;if(c.b)for(var d=b,f=c.b,e=0;e<f.length;++e){var g=f[e];if(!d.d[g.id]&&!d.g[g.id]&&!g.tc)if(g.cc)d.k[g.id]=g.cc;else if(g.multiple){var h=d,j=g.id,g=g.aa||Cd(vd,g.Kb);h.g[j]=g;if(g=h.b[j]){if(1<g.length){for(var n=0;n<g.length;++n)g[n].index=n;g.sort(Yd)}for(;g.length;)g.shift().Lb.aa(m);delete h.b[j]}}else S(d,g.id,g.aa?g.aa(d):new g.Kb(d))}c.g&&c.g(b)}for(a=0;a<T.length;++a);for(a=0;a<Be.length;++a)Be[a](b);Ae=l}a=
document?new jd(ld(document)):ve||(ve=new jd);S(b,"ia",a);S(b,"fa",new te("/_/jserror"));c=new Sd(b,window.__SSR,window.__P1_XP);S(b,"ka",c);"only"!=c.f&&S(b,"ha",new je(a.b));c=b.get("ka");if("only"==c.f)return b;c=c.b||"widget";d=b.get("fa");d=z(d.ab,d);c=new sc(c,1);c.d=d;(a=R(a.b).__P1_BASEURL)&&tc(c,a);S(b,"ga",c);new ue(b);return b}function Ce(b,a){var c=a||{};c.id=b.f;c.source=b.g.b;c.track=gadgets.json.stringify(ud(Od(b.Pa)));var d=b.g.d;d&&(c.container=d);return c}
function we(b,a){var c,d={Hb:!!a&&a.isSetByViewer,ua:b.Ma,N:b.Na};c=new V;d.Hb?d.ua&&d.N?(d="You publicly +1'd this as "+(W(d.ua)+(" ("+(W(d.N)+"). Click again to undo."))),c.b(d)):d.N?(d="You publicly +1'd this as "+(W(d.N)+". Click again to undo."),c.b(d)):c.b("You publicly +1'd this. Click again to undo."):d.ua&&d.N?(d="Click here to publicly +1 this as "+(W(d.ua)+(" ("+(W(d.N)+")."))),c.b(d)):d.N?(d="Click here to publicly +1 this as "+(W(d.N)+"."),c.b(d)):c.b("Click here to publicly +1 this.");
c=c.toString();ye(b)||xe(b)?b.k.setAttribute("aria-label",c):b.k.setAttribute("title",c)}function De(b){b.ba=l;var a=R(b.d.b);b.Y&&a.clearTimeout(b.Y);b.Y=a.setTimeout(z(b.Jb,b),b.La)}function Ee(b,a){var c=parseInt(a,10);if(c==a)return""+c}function Fe(b,a){"string"==typeof b.w.ad&&(a.ad="false"!=b.w.ad.toLowerCase())}function Ge(b,a){var c=R(b.d.b);if(c.iframer&&c.iframer.onPlusOne)c.iframer.onPlusOne({state:a?"on":"off",href:b.f})}
function He(b){var a=b.f,c=gc(b.b,a),d;if(!(d=!!b.sa))if(!(d=!!c.d.length)){if(c=!!c.b)c=!b.b.v(a).T;d=c}return d}function Ie(b,a){return z(function(){try{a.apply(this,arguments)}catch(b){try{b.errsource="plusone_publisher",this.Nb(b)}catch(d){}}},b)}function ye(b){return b.Sa&&!!b.g.g.UC&&!!iframes.getHandler("bubble")}function xe(b){return b.Sa&&!!b.g.g.UH&&!!iframes.getHandler("bubble")}var hd={};jd.prototype.createElement=function $fa(a){return this.b.createElement(a)};
jd.prototype.contains=function $ga(a,c){if(a.contains&&1==c.nodeType)return a==c||a.contains(c);if("undefined"!=typeof a.compareDocumentPosition)return a==c||Boolean(a.compareDocumentPosition(c)&16);for(;c&&a!=c;)c=c.parentNode;return c==a};var ve;td.prototype.toString=function $ha(){return this.b.toString()};r=xd.prototype;r.L=function $ia(){return this.p.L()};r.remove=function $ja(a){return this.p.remove(od(a))};r.clear=function $ka(){this.p.clear()};r.contains=function $la(a){return this.p.D(od(a))};
r.F=function $ma(){return this.p.F()};r.J=function $na(){return new xd(this)};r.Ga=function $oa(a){return this.L()==qd(a)&&zd(this,a)};r.ha=function $pa(){return this.p.ha(o)};G(E.i(),"sy4");A(Dd,td);var Fd=["top","right","bottom","left"];Id.prototype.b=o;Id.prototype.open=function $qa(){!this.d&&!this.b&&(this.d=iframes.open(this.q,Ad(this.h),Ad(this.f),Ad(this.g),z(this.n,this)),this.b=l,Hd(this.k,"onstartinteraction"))};Id.prototype.n=function $ra(){this.d&&(this.d=m,Hd(this.k,"onendinteraction"));this.b=o};Id.prototype.close=function $sa(){this.d&&(this.d.close?this.d.close():this.d=m);this.b=o};A(Ld,Id);A(Md,td);A(Rd,Id);A(Ud,D);Ud.prototype.get=function $ta(a){var c=Qd(this,a);c||i(new ae(a));return c};Ud.prototype.u=function $ua(){Ud.M.u.call(this);if(Vd(this)==this){var a=this.h;if(a)for(;a.length;)a[0].K()}else for(var a=Vd(this).h,c=0;c<a.length;c++)if(a[c]==this){a.splice(c,1);break}for(var d in this.d)a=this.d[d],a[1]&&"undefined"!=typeof a[0].K&&a[0].K();this.d=m;this.z&&this.q.K();Zd(this,this);this.b=m;oa(this.w);this.w=m};A(ae,nb);var T=[],Be=[],Ae=o;var ee={AED:[2,"dh","\u062f.\u0625.","DH"],AUD:[2,"$","AU$"],BDT:[2,"\u09f3","Tk"],BRL:[2,"R$","R$"],CAD:[2,"$","C$"],CHF:[2,"CHF","CHF"],CLP:[0,"$","CL$"],CNY:[2,"\u00a5","RMB\u00a5"],COP:[0,"$","COL$"],CRC:[0,"\u20a1","CR\u20a1"],CZK:[2,"K\u010d","K\u010d"],DKK:[18,"kr","kr"],DOP:[2,"$","RD$"],EGP:[2,"\u00a3","LE"],EUR:[18,"\u20ac","\u20ac"],GBP:[2,"\u00a3","GB\u00a3"],HKD:[2,"$","HK$"],ILS:[2,"\u20aa","IL\u20aa"],INR:[2,"\u20b9","Rs"],ISK:[0,"kr","kr"],JMD:[2,"$","JA$"],JPY:[0,"\u00a5","JP\u00a5"],
KRW:[0,"\u20a9","KR\u20a9"],LKR:[2,"Rs","SLRs"],MNT:[0,"\u20ae","MN\u20ae"],MXN:[2,"$","Mex$"],MYR:[2,"RM","RM"],NOK:[18,"kr","NOkr"],PAB:[2,"B/.","B/."],PEN:[2,"S/.","S/."],PHP:[2,"\u20b1","Php"],PKR:[0,"Rs","PKRs."],RUB:[2,"Rup","Rup"],SAR:[2,"Rial","Rial"],SEK:[2,"kr","kr"],SGD:[2,"$","S$"],THB:[2,"\u0e3f","THB"],TRY:[2,"TL","YTL"],TWD:[2,"NT$","NT$"],USD:[2,"$","US$"],UYU:[2,"$","UY$"],VND:[0,"\u20ab","VN\u20ab"],YER:[0,"Rial","Rial"],ZAR:[2,"R","ZAR"]};var Je={ob:".",rb:",",zb:"%",ta:"0",Cb:"+",ub:"-",qb:"E",Bb:"\u2030",sb:"\u221e",wb:"NaN",nb:"#,##0.###",Fb:"#E0",Ab:"#,##0%",mb:"\u00a4#,##0.00;(\u00a4#,##0.00)",pb:"USD"},U=Je,U=Je;var le=/\s*;\s*/;r=je.prototype;r.set=function $va(a,c,d,f,e,g){/[;=\s]/.test(a)&&i(Error("L`"+a));/[;\r\n]/.test(c)&&i(Error("M`"+c));d!==k||(d=-1);e=e?";domain="+e:"";f=f?";path="+f:"";g=g?";secure":"";d=0>d?"":0==d?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date(I()+1E3*d)).toUTCString();this.b.cookie=a+"="+c+e+f+d+g};r.get=function $wa(a,c){for(var d=a+"=",f=(this.b.cookie||"").split(le),e=0,g;g=f[e];e++)if(0==g.indexOf(d))return g.substr(d.length);return c};
r.remove=function $xa(a,c,d){var f=this.D(a);this.set(a,"",0,c,d);return f};r.Q=function $ya(){return ke(this).keys};r.F=function $za(){return ke(this).lb};r.L=function $Aa(){return!this.b.cookie?0:(this.b.cookie||"").split(le).length};r.D=function $Ba(a){return this.get(a)!==k};r.wa=function $Ca(a){for(var c=ke(this).lb,d=0;d<c.length;d++)if(c[d]==a)return l;return o};r.clear=function $Da(){for(var a=ke(this).keys,c=a.length-1;0<=c;c--)this.remove(a[c])};var Ke=t.window;K&&L(8);var me;(me="ScriptEngine"in t&&"JScript"==t.ScriptEngine())&&(t.ScriptEngineMajorVersion(),t.ScriptEngineMinorVersion(),t.ScriptEngineBuildVersion());V.prototype.set=function $Ea(a){this.clear();this.b(a)};me?(V.prototype.f=0,V.prototype.b=function $Fa(a,c,d){c==m?this.d[this.f++]=a:(this.d.push.apply(this.d,arguments),this.f=this.d.length);return this}):V.prototype.b=function $Fa(a,c,d){this.d+=a;if(c!=m)for(var f=1;f<arguments.length;f++)this.d+=arguments[f];return this};V.prototype.clear=function $Ga(){me?this.f=this.d.length=0:this.d=""};V.prototype.toString=function $Ha(){if(me){var a=this.d.join("");this.clear();a&&this.b(a);return a}return this.d};var pe={"\x00":"&#0;",'"':"&quot;","&":"&amp;","'":"&#39;","<":"&lt;",">":"&gt;","\t":"&#9;","\n":"&#10;","\x0B":"&#11;","\u000c":"&#12;","\r":"&#13;"," ":"&#32;","-":"&#45;","/":"&#47;","=":"&#61;","`":"&#96;","\u0085":"&#133;","\u00a0":"&#160;","\u2028":"&#8232;","\u2029":"&#8233;"},ne=/[\x00\x22\x26\x27\x3c\x3e]/g;var Le;A(se,re);se.prototype.b=m;Le=new se;te.prototype.ab=function $Ia(a){try{var c={};c["call-stack"]=wd();var d;var f=sb("window.location.href");if(x(a))d={message:a,name:"Unknown error",lineNumber:"Not available",fileName:f,stack:"Not available"};else{var e,g,h=o;try{e=a.lineNumber||a.b||"Not available"}catch(j){e="Not available",h=l}try{g=a.fileName||a.filename||a.sourceURL||f}catch(n){g="Not available",h=l}d=h||!a.lineNumber||!a.fileName||!a.stack?{message:a.message,name:a.name,lineNumber:e,fileName:g,stack:a.stack||"Not available"}:
a}var p=d.stack,q=sd(this.b,"script",d.fileName,"error",d.message,"line",d.lineNumber),a={};a.trace=p;if(c)for(var y in c)a["context."+y]=c[y];var w=Dc([],a);w[0]="";var nd=w.join(""),La,rb;a:{if(!Le.b&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){c=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"];for(p=0;p<c.length;p++){var ge=c[p];try{new ActiveXObject(ge);rb=Le.b=ge;break a}catch(Sf){}}i(Error("O"))}rb=Le.b}La=rb?new ActiveXObject(rb):new XMLHttpRequest;
La.open("POST",q,l);La.setRequestHeader("Content-type","application/x-www-form-urlencoded");La.setRequestHeader("Content-length",nd.length.toString());La.send(nd)}catch(Tf){}};A(ue,P);r=ue.prototype;r.Wb=200;r.ba=o;r.la=0;r.Ia=o;r.Rb=function $Ja(a){if(!this.Fa(a,l)){if(!this.I||uc(this.h)!=a.signedUp)this.H=I();this.I=l;this.h.b=a.signedUp;var c=a.displayName;this.Na=a.email||"";this.Ma=c||"";we(this,this.b.v(this.f).get())}};
r.Aa=function $Ka(){this.H=I();if(this.sa){var a=this.sa-I();if(0<a){R(this.d.b).setTimeout(z(this.Aa,this),a);return}this.sa=0}if((a=this.b.v(this.f).get())||this.G){!a.isSetByViewer&&this.z&&this.O(l);var c=kd(this.d,"plusone");if(c){var d;if(this.G){d="AV";this.k.setAttribute("title","+1");try{this.O(l)}catch(f){c.className=d,i(f)}}else this.b.v(this.f).get()&&He(this)?(d="BV",this.sa=I()+650):(a.isSetByViewer?(d="Bz",this.k.setAttribute("aria-pressed","true")):(d="Uu",this.k.setAttribute("aria-pressed",
"false")),we(this,a));c.className=d}if(a&&a.metadata&&a.metadata.globalCounts&&a.metadata.globalCounts.count!=k&&(c=a.metadata.globalCounts.count,d=kd(this.d,"aggregateCount"))){var e;e=(e="en-US".match(/^\w{2,3}([-_]|$)/))?e[0].replace(/[_-]/g,""):"";var g;g=this.Db;var h=c.toString().length;if("en"==e&&3<h)g=6>=h?""+c.toPrecision(2)/Math.pow(10,3):""+c.toPrecision(2)/Math.pow(10,6);else{var j=c;if(isNaN(j))g=U.wb;else{var h=[],n=0>j||0==j&&0>1/j;h.push(n?g.n:g.H);if(isFinite(j))if(j*=n?-1:1,j*=
g.g,g.w)if(0==j)he(g,j,g.b,h),ie(g,0,h);else{var p=Math.floor(Math.log(j)/Math.log(10)),j=j/Math.pow(10,p),q=g.b;if(1<g.h&&g.h>g.b){for(;0!=p%g.h;)j*=10,p--;q=1}else 1>g.b?(p++,j/=10):(p-=g.b-1,j*=Math.pow(10,g.b-1));he(g,j,q,h);ie(g,p,h)}else he(g,j,g.b,h);else h.push(U.sb);h.push(n?g.q:g.I);g=h.join("")}}e={count:g,P:c.toString().length,lang:e};h=new V;"en"==e.lang?9<e.P?h.b("Lots"):6<e.P?h.b(W(e.count),"M"):3<e.P?h.b(W(e.count),"k"):h.b(W(e.count)):4<e.P?h.b("10K+"):h.b(W(e.count));d.innerHTML=
h.toString();kd(this.d,"aggregateBubble").setAttribute("title",qe({count:g,P:c.toString().length}))}if(a){c=hb("checked",this.d.b);e=hb("unchecked",this.d.b);if(c&&e){for(d=0;d<c.length;d++)c[d].style.display=a.isSetByViewer?"":"none";for(d=0;d<e.length;d++)e[d].style.display=!a.isSetByViewer?"":"none"}if(this.yb){a=a.isSetByViewer?c:e;for(d=0;d<c.length;d++)g=(e=a[d]||this.d.b)||document,h=m,e=(h=gb(g)?g.querySelector(".oQ"):hb("oQ",e)[0])||m,g=e.style.whiteSpace,e.style.whiteSpace="nowrap",iframes.resize({width:Math.min(kd(this.d,
"plusone_table").offsetWidth+1,this.Eb)}),e.style.whiteSpace=g}}}};r.Vb=function $La(){this.la=I();this.ba=o;if(!this.n){var a=z(this.bc,this),c=this.Wb;cb(a)||(a&&"function"==typeof a.handleEvent?a=z(a.handleEvent,a):i(Error("s")));this.n=2147483647<c?-1:Ke.setTimeout(a,c||0)}};r.Ub=function $Ma(){this.la=I();De(this);this.n&&(Ke.clearTimeout(this.n),this.n=k)};
r.bc=function $Na(){if(!this.G&&!(this.q&&this.q.b||this.z&&this.z.b||this.ba)){var a=this.f,c=this.b.v(a).get(),d=o;c&&c.isSetByViewer&&(d=l);a=new Rd(this.k,z(this.fb,this),z(this.gb,this),a,d,this.H,this.g.b);(c=this.g.d)&&Jd(a,c);Kd(a,this.Oa);a.open();this.Z=this.z=a;this.La=1E3}};r.gb=function $Oa(a){this.Pa.b.push(new Dd(a))};r.fb=function $Pa(a){this.la<a.timestamp&&(this.la=a.timestamp,"mouseover"==a.type?this.ba=o:"mouseout"==a.type&&De(this))};
r.O=function $Qa(a){var c=this.Z;c&&c.b&&(a?(c.close(),this.Y&&R(this.d.b).clearTimeout(this.Y),this.la=0,this.ba=o,this.z=this.q=this.Z=m):De(this))};r.Jb=function $Ra(){if(this.ba){var a=this.Z;if(a&&(a.b?(a=a.d)?(a=a.canAutoClose,a=!cb(a)?m:a):a=m:a=m,a)){a(z(this.O,this));return}this.O(l)}};
r.Za=function $Sa(){if(!He(this)){var a;if(!this.I&&!this.tb.D("BEAT")||!uc(this.h)){a=R(this.d.b);if(a.iframer&&a.iframer.onpopup)a.iframer.onpopup();vc(this.h,R(this.d.b));a=l}else a=o;if(a)this.Ia=l;else if(this.G?((a=wc())&&a.focus(),a=l):a=o,!a){var c=this.f;if(a=this.b.v(c).get())c=ec(gc(this.b,c),z(a.isSetByViewer?this.Ba:this.fc,this)),a.isSetByViewer&&2!=c&&R(this.d.b).setTimeout(z(this.Aa,this),150)}}};
r.ec=function $Ta(){if(!this.I||uc(this.h))this.H=I();this.I=l;this.Ia&&(this.Za(),this.Ia=o);uc(this.h)&&hc(this.b,this.b.b.getSignupState({source:this.g.b,nolog:l})).execute(Ie(this,this.Rb))};
r.fc=function $Ua(){var a=this.b.v(this.f).get();if(a&&!a.isSetByViewer){var a=Ce(this,{optimistic:l,cdx:(I()-this.Qa).toString(16),profileVersion:this.h.g||k}),c=this.g.h;c&&(a.abtk=c);Fe(this,a);this.w.cr&&(a.cr=Ee(this,this.w.cr));this.w.ag&&(a.ag=Ee(this,this.w.ag));if(!this.G&&ye(this)&&(!this.q||!this.q.b)){this.z&&this.O(l);var c=new Ld(this.k,z(this.fb,this),z(this.gb,this),this.f,this.H,this.g.b),d=this.g.d;d&&Jd(c,d);Kd(c,this.Oa);c.open();this.Z=this.q=c;this.La=3E3}hc(this.b,this.b.b.insert(a)).execute(Ie(this,
this.Fa));Ge(this,l)}};r.Ba=function $Va(){var a=this.b.v(this.f).get();a&&a.isSetByViewer&&(a=Ce(this,{cdx:(I()-this.Qa).toString(16),profileVersion:this.h.g||k}),Fe(this,a),this.b.remove(a).execute(Ie(this,this.Fa)),Ge(this,o));this.q&&this.O(l)};
r.Fa=function $Wa(a,c){var d;d=this.Ra?this.Ra.b:k;if(a&&!a.error)d="";else{if(a){var f="Error in RPC: "+a.id;a.error&&(f=a.error.message?f+(" - "+a.error.message):f+(" - "+a.error))}else f="Empty response";d&&d.call(this.Ra,f);d=f}c||(this.G=d,this.Aa());d&&this.O(l);return d};r.u=function $Xa(){this.b=this.ga=m;this.O(l);this.n&&(Ke.clearTimeout(this.n),this.n=k);ue.M.u.call(this)};
F(E.i(),"sy4");H(E.i(),"sy4");
}catch(e){_DumpException(e)}
try{
G(E.i(),"p1p");ze();
F(E.i(),"p1p");H(E.i(),"p1p");
}catch(e){_DumpException(e)}

// Copyright 2002-2011 Google Inc.
