// JavaScript Document
document.write('<div class="infomous_cloud">');
document.write('<embed type="application/x-shockwave-flash"\
src="http://www.infomous.com/site/mockups/NYT/infomous2.swf"\
id="infomous"\
name="infomous"\
quality="high"\
bgcolor="#E4E8E9"\
allowscriptaccess="always"\
flashvars="loadAtStart=true\
&amp;\
setPanels=blobs,words,status,branding\
&amp;\
hidden=no,do,probably,will,new,more,most,gets,up,did,after\
&amp;\
feeds=http%3A%2F%2Fbits.blogs.nytimes.com%2Ffeed\
&amp;\
textOption=TITLE_AND_DESCRIPTION\
&amp;\
maxWords=28\
&amp;\
groups=1\
&amp;\
fontScale=1.3\
&amp;\
showLinks=1\
&amp;\
linkColor=0xfFf4f8\
&amp;\
linkOverColor=0xDFE4E8\
&amp;\
wordColor=0x222233\
&amp;\
wordOverColor=0x00519B\
&amp;\
wordOverLinkedColor=0x00519B\
&amp;\
wordFadeColor=0x555577"\
width="362"\
height="340">');
document.write('</div>');
